[project]
name = "tinyvit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
classifiers = ["Private :: Do Not Upload"]
dependencies = [
    "timm==1.0.22",
    "datasets==4.4.1",
    "matplotlib==3.10.8",
    "numpy==2.3.5",
    "pandas==2.3.3",
    "pydantic==2.11.10",
    "pyyaml==6.0.3",
    "scikit-learn==1.7.2",
    "seaborn==0.13.2",
    "torch==2.7.1",
    "torchvision==0.22.1",
    "transformers==4.55.4",
    "typer==0.16.1",
    "wandb==0.22.3",
]

[project.scripts]
tinyvit = "tinyvit.main:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "mypy==1.18.2",
    "nbdev==2.4.6",
    "pre-commit>=4.1.0",
    "ruff==0.14.9",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cuda", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cuda", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
